config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :books do
    collection do
      post 'import'
      post 'export'
      get 'summary'
    end
    member do
      post 'queue_update'
      post 'browse'
      post 'borrow'
      post 'rate'
      post 'revert_to_new'
      post 'toggle_starred'
      post 'archive'
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one :meta, class_name: BookUserMeta, dependent: :destroy
  has_many :library_books, dependent: :destroy
  has_many :libraries, through: :library_books

  validates :brn, presence: true, uniqueness: true
  validates :author, length: { minimum: 0 }, allow_nil: false
  validates :title, presence: true
  validates :pages, presence: true
  validates :height, presence: true
  validates :call_no, presence: true

  attr_accessor :library_statuses,
                :valid_book

  after_create :create_book_user_meta

  after_save :create_new_library,
             :update_library_books

  state_machine :status, :initial => :completed do
    after_transition :completed => :queued, do: :update_availability_async
    before_transition :queued => :completed, do: :update_timestamps

    event :queue_update do
      transition :completed => :queued
    end

    event :finish_update do
      transition :queued => :completed
    end
  end

  scope :browsed, -> { joins(:meta).merge(BookUserMeta.browsed) }
  scope :good_or_better, -> { joins(:meta).merge(BookUserMeta.good_or_better) }
  scope :queued, -> { where(status: :queued) }

  delegate :read?, to: :meta

  def unavailable?
    library_statuses.nil? || library_statuses.empty?
  end

  def self.import(brn)
    if Book.where(brn: brn).exists?
      [nil, :already_imported]
    else
      book = NLBServiceV3.new.import_book(brn)
      if book.nil?
        [nil, :invalid_brn]
      elsif book.unavailable?
        [nil, :unavailable]
      else
        book.update_timestamps
        if book.save
          [book, nil]
        else
          [nil, :save_failed]
        end
      end
    end
  end

  def self.import_from_yaml(books_yaml)
    begin
      books = Psych.load(books_yaml)
    rescue Psych::SyntaxError
      books = {}
    end

    books.each do |brn, meta|
      unless Book.where(brn: brn).exists?
        Book.delay.import_and_save(brn, meta)
      end
    end
  end

  def self.export_to_yaml
    books = Book.includes(:meta).order(:id)
    books_hash = books.reduce({}) do |hash,  book|
      meta = book.meta.attributes.except!('id', 'book_id', 'updated_at', 'created_at')
      hash[book.brn.to_i] = meta
      hash
    end
    Psych.dump(books_hash)
  end

  def update_timestamps
    self.last_updated_at = Time.now
  end

  def update_availability
    NLBServiceV3.new.update_book(self)
    self.finish_update
  end

  def update_availability_async
    self.delay.update_availability
  end

  def self.import_and_save(brn, meta)
    book, error = Book.import(brn)
    if book && meta
      book.meta.update(meta)
    elsif error && error != :already_imported
      ImportLogger.error(brn, error)
    end
  end

  def available?(library_id=nil)
    if library_id.present?
      library_books.where(library_id: library_id).first.try(:available) || false
    else
      available_count > 0
    end
  end

  def reference?(library_id=nil)
    if library_id.present?
      library_books.where(library_id: library_id).first.try(:reference) || false
    else
      # Reference should return false when no libraries are specified and at least one library has the book in the non-reference section
      !library_books.exists?(reference: false)
    end
  end

  private
  def create_book_user_meta
    BookUserMeta.create(book_id: id)
  end

  def create_new_library
    library_statuses.each { |ls| Library.find_or_create_by(name: ls[:library], regional: ls[:regional]) } unless library_statuses.nil?
  end

  def update_library_books
    unless library_statuses.nil?
      library_books = []
      library_statuses.each do |ls|
        library = Library.where(name: ls[:library]).first
        lb = LibraryBook.find_or_initialize_by(library_id: library.id, book_id: self.id)
        lb.update_attributes(ls.except(:library, :regional))
        library_books << lb
      end
      self.library_books = library_books
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    params[:q] ||= {}
    search_params = build_search_params(params[:q])
    session[:search_library_id] =  search_params.fetch(:library_books_library_id_eq, nil)
    session.delete(:search_library_id) if session[:search_library_id].blank?

    @q = Book.search(search_params)
    @books = @q.result.includes(:meta).includes(:library_books).uniq.paginate(:page => params[:page], :per_page => 15).order(:call_no)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    brn = params[:book][:brn].strip

    @book, error = Book.import(brn)
    if @book
      redirect_to book_path(@book) and return
    else
      flash[:alert] = t("activerecord.errors.models.book.#{error}")
      @book = Book.new
      render :new
    end
  end

  def import
    file = params[:book][:file]
    yaml = file.read
    file.close
    Book.import_from_yaml(yaml)
    redirect_to books_url
  end

  def export
    js false
    filename = "books#{Time.now.strftime('%Y%m%d')}.yaml"
    send_data(Book.export_to_yaml, filename: filename, type: 'application/yaml')
  end

  def queue_update
    @book = Book.find(params[:id])
    @book.queue_update
    render_row_or_redirect_index
  end

  def borrow
    @book = Book.find(params[:id])
    @book.meta.borrow
    render_row_or_redirect_index
  end

  def browse
    @book = Book.find(params[:id])
    @book.meta.browse
    render_row_or_redirect_index
  end

  def rate
    @book = Book.find(params[:id])
    @book.meta.rating = params[:rating]
    @book.meta.save
    respond_to do |format|
      format.json { render nothing: true, status: :ok }
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    remove_row_or_redirect_index
  end

  def revert_to_new
    @book = Book.find(params[:id])
    @book.meta.revert
    render_row_or_redirect_index
  end

  def toggle_starred
    @book = Book.find(params[:id])
    @book.meta.toggle!(:starred)
    render_row_or_redirect_index
  end

  def archive
    @book = Book.find(params[:id])
    @book.meta.archive
    remove_row_or_redirect_index
  end

  def summary
    respond_to do |format|
      format.js { js false }
    end
  end

  private
  def render_row_or_redirect_index
    respond_to do |format|
      format.js { render_row }
      format.html { redirect_to books_url }
    end
  end

  def render_row
    js false
    render partial: 'render_row'
  end

  def build_search_params(params)
    search_params = params.dup

    # Ransack currently doesn't work nicely with scopes using boolean arguments so manually constructing search now
    if search_params.fetch(:library_count_eq, nil) == "-1"
      search_params.delete(:library_count_eq)
      search_params[:library_count_not_eq] = 1
    end

    # Search for all books that have not been borrowed or archived if no status is selected
    if search_params.fetch(:meta_status_eq, "").blank?
      search_params.delete(:meta_status_eq)
      search_params[:meta_status_not_in] = [:borrowed, :archived]
    end

    # Search for regional books
    if search_params.fetch(:regional_only, nil).present?
      if search_params.delete(:regional_only) == "1"
        search_params[:non_regional_library_count_eq] = 0
      else
        search_params[:non_regional_library_count_not_eq] = 0
      end
    end

    # Search for available books
    if search_params.fetch(:available, nil).present?
      available = search_params.delete(:available) == "1"

      if search_params.fetch(:library_books_library_id_eq, nil).present?
        search_params[:library_books_available_eq] = available
      else
        if available
          search_params[:available_count_not_eq] = 0
        else
          search_params[:available_count_eq] = 0
        end
      end
    end

    # Search by library_count
    library_count = search_params.delete(:library_count).to_i
    case library_count
    when -1
      search_params[:library_count_lt] = 2
    when -2
      search_params[:library_count_in] = 2..5
    when -3
      search_params[:library_count_gt] = 5
    end

    search_params
  end

  def remove_row_or_redirect_index
    respond_to do |format|
      format.js { remove_row }
      format.html { redirect_to books_url }
    end
  end

  def remove_row
    js false
    render :remove
  end
end

app/views/books/_render_row.js.erb
var row = $("tr#book-<%= @book.id %>");
row.html("<%= escape_javascript(render partial: 'row', locals: {b: @book.decorate}) %>");
row.find("div.responsive-rater").responsiveRater();

app/views/books/_row.html.haml
%td.text-center
  - unless b.meta.borrowed? || b.meta.archived?
    - if b.meta.starred?
      = link_to toggle_starred_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Unstar' do
        = icon('star', '', class: 'fa-lg')
    - else
      = link_to toggle_starred_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Star' do
        = icon('star-o', '', class: 'fa-lg')
%td= b.call_no
%td
  = b.availability_badge(session[:search_library_id])
  = b.reference_badge(session[:search_library_id])
  = link_to truncate(b.title, length: 85, separator: ' '), book_url(b)
  = b.library_count_badge
  = b.pages_badge
  = b.height_badge
%td= responsive_rater_tag(value: b.meta.rating, min: 0, max: 5, id: b.id)
%td= b.pages
%td= b.human_status_name
%td{ class: (1.day.ago > b.last_updated_at ? 'danger' : '') }= time_ago_in_words(b.last_updated_at) + ' ago'
%td
  .pull-right
    - if 1.hour.ago > b.last_updated_at && !b.queued?
      = link_to queue_update_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Queue For Update', class: 'js-queue' do
        = icon('refresh', '', class: 'fa-lg')
    - if b.meta.can_browse?
      = link_to browse_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Mark Browsed' do
        = icon('file-text', '', class: 'fa-lg')
    - if b.meta.can_revert?
      = link_to revert_to_new_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Revert to New' do
        = icon('file-o', '', class: 'fa-lg')
    - if b.meta.can_borrow?
      = link_to borrow_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Mark Borrowed' do
        = icon('check', '', class: 'fa-lg')
    - if b.meta.can_archive?
      = link_to archive_book_url(b), remote: true, method: :post, rel: 'tooltip', title: 'Archive' do
        = icon('archive', '', class: 'fa-lg')
    = link_to book_url(b), remote: true, method: :delete, rel: 'tooltip', title: 'Delete', data: { confirm: "Delete #{b.title}?" } do
      = icon('remove', '', class: 'fa-lg')

app/views/books/_row.js.erb
var row = $("tr#book-<%= @book.id %>");
row.html("<%= escape_javascript(render partial: 'row', locals: {b: @book}) %>");
row.find("div.responsive-rater").responsiveRater();

app/views/books/destroy.js.erb
$("tr#book-<%= @book.id %>").remove();

app/views/books/index.html.haml
.container-fluid
  = search_form_for(@q) do |f|
    = f.input :title_cont, label: 'Title', required: false
    = f.input :meta_rating_eq, collection: [['Unrated', 0], ['★', 1], ['★★', 2], ['★★★', 3], ['★★★★', 4], ['★★★★★', 5]], label: 'Rating', required: false
    = f.input :pages_lteq, collection: [['< 110 pages', 110], ['< 220 pages', 220], ['< 330 pages', 330], ['< 440 pages', 440], ['< 550 pages', 550]], label: 'Length', required: false
    = f.input :library_books_library_id_eq, collection: Library.all.order(:name), value_method: :id,  label: 'Library', required: false
    = f.input :available, collection: [['YES', 1], ['NO', -1]], label: 'Available', include_blank: true, required: false, selected: params[:q][:available]
    = f.input :regional_only, collection: [['YES', 1], ['NO', -1]], label: 'Regional Only', include_blank: true, required: false, selected: params[:q][:regional_only]
    = f.input :library_count, collection: [['Solo (0-1)', -1], ['Rare (2-5)', -2],['Common (6+)', -3] ], label: 'Quantity', include_blank: true, required: false, selected: params[:q][:library_count]
    = f.input :meta_status_eq, collection: [['New', 'new'], ['Browsed', 'browsed'], ['Borrowed', 'borrowed'], ['Archived', 'archived']], label: 'Status', include_blank: true, required: false
    = f.input :meta_starred_eq, collection: [['YES', true], ['NO', false]], label: 'Starred', include_blank: true, required: false
    = f.submit 'Search', class: 'btn btn-success'
    = button_tag 'Update All', type: :button, id: 'js-queue-all', class: 'btn btn-warning'
    = link_to 'Reset', books_url, class: 'btn btn-danger'
  %hr
  .row
    .col-xs-12
      %table.table.table-striped
        %tr
          %th{ width: 35 }= sort_link(@q, :id, 'Added', default_order: :desc)
          %th{ width: 160 }= sort_link(@q, :call_no)
          %th= sort_link(@q, :title)
          %th{ width: 100 }= sort_link(@q, :meta_rating)
          %th{ width: 80 }= sort_link(@q, :pages)
          %th{ width: 120 } Status
          %th{ width: 170 } Updated
          %th{ width: 100 } Actions
        - @books.each do |b|
          %tr{ id: "book-#{b.id}" }
            = render partial: 'row', locals: { b: b.decorate }
      = page_entries_info @books
      .pagination.pull-right
        = will_paginate @books

app/views/books/new.html.haml
.container-fluid
  .row
    = simple_form_for(@book, url: books_url, method: :post) do |f|
      = f.input :brn
      = f.button :submit, 'Import!'
    %hr
  .row
    = simple_form_for(:book, url: import_books_url, method: :post) do |f|
      = f.input :file, as: :file
      = f.submit 'Import from file ...'
    %hr  

app/views/books/queue_update.js.erb
var row = $("tr#book-<%= @book.id %>");
row.html("<%= escape_javascript(render partial: 'row', locals: {b: @book}) %>");
row.find("div.responsive-rater").responsiveRater();

app/views/books/remove.js.erb
$("tr#book-<%= @book.id %>").remove();

app/views/books/show.html.haml
- content_for :title, @book.title
.container
  .row
    .col-xs-8
      %section
        .h4
          Book Data
        %table.table.table-striped
          =attr_row(@book, :title)
          =attr_row(@book, :author)
          =attr_row(@book, :call_no)
          =attr_row(@book, :pages)
          =attr_row(@book, :height)
          =attr_row(@book, :section)
          =attr_row(@book, :brn)
      
      %section
        %h4
          User Data
        %table.table.table-striped
          %tr
            %td.col-xs-4
              Rating
            %td.col-xs-8
              = responsive_rater_tag(value: @book.meta.rating, min: 0, max: 5, id: @book.id)
          =attr_row(@book.meta, :borrowed)
          =attr_row(@book.meta, :starred)

      %section
        %h4
          Availability
        %table.table.table-striped
          %thead
            %tr
              %th Library
              %th Reference
          %tbody
            - @book.library_books.each do |lb|
              %tr{ class: (lb.available ? 'success' : '') }
                %td.col-xs-7= lb.library_name
                %td.col-xs-1= (lb.reference ? 'Reference' : '')

      %section
        .pull-right
          - if @book.meta.can_browse?
            = link_to 'Mark Browsed', browse_book_url(@book), method: :post, class: 'btn btn-default'
          - if @book.meta.can_borrow?
            = link_to 'Mark Borrowed', borrow_book_url(@book), method: :post, class: 'btn btn-default'